server:
  port: 6001
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://mysql:3306/SchoolDB
    username: TestUser
    password: TestUser@123
  application:
    name: STUD-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://myimage:8761/eureka/
  instance:
    hostname: myimage